name: Sync

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        repository: ${{ secrets.GIT_SRC_REPOSITORY }}
        token: ${{ secrets.GIT_SRC_PAT }}
        ref: master
        fetch-depth: 0
    - name: Push
      run: |
        git remote add target https://${GITLAB_USERNAME}:${GITLAB_ACCESS_TOKEN}@${GITLAB_URL}
        git push --all target
        git push --tags target
      env:
        GITLAB_URL: ${{ secrets.GITLAB_URL }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
